### Registrar usuario
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "nombre": "Fabri",
  "email": "fabricioponce2012@gmail.com",
  "password": "adminadmin"
}

###

### Login de usuario
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "fabricioponce2012@gmail.com",
  "password": "adminadmin"
}
