### Listar conductores
GET http://localhost:3000/conductores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJmYWJyaWNpb3BvbmNlMjAxMkBnbWFpbC5jb20iLCJub21icmUiOiJGYWJyaSIsImlhdCI6MTc2Mjk5NDEzMywiZXhwIjoxNzYzMDA4NTMzfQ.k7IwXewsyNAtPR4KWYvTvdyL0zfOlPUfxB4GSC-Ppyo
Content-Type: application/json

###

### Crear conductor
POST http://localhost:3000/conductores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJmYWJyaWNpb3BvbmNlMjAxMkBnbWFpbC5jb20iLCJub21icmUiOiJGYWJyaSIsImlhdCI6MTc2Mjk5NDEzMywiZXhwIjoxNzYzMDA4NTMzfQ.k7IwXewsyNAtPR4KWYvTvdyL0zfOlPUfxB4GSC-Ppyo
Content-Type: application/json

{
  "nombre": "Marcos",
  "apellido": "Castro",
  "dni": "39783713",
  "licencia": "B1",
  "fecha_vencimiento_licencia": "2028-05-01"
}
