### Listar viajes
GET http://localhost:3000/viajes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJmYWJyaWNpb3BvbmNlMjAxMkBnbWFpbC5jb20iLCJub21icmUiOiJGYWJyaSIsImlhdCI6MTc2Mjk5NDEzMywiZXhwIjoxNzYzMDA4NTMzfQ.k7IwXewsyNAtPR4KWYvTvdyL0zfOlPUfxB4GSC-Ppyo
Content-Type: application/json

###

### Crear viaje
POST http://localhost:3000/viajes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJmYWJyaWNpb3BvbmNlMjAxMkBnbWFpbC5jb20iLCJub21icmUiOiJGYWJyaSIsImlhdCI6MTc2Mjk5NDEzMywiZXhwIjoxNzYzMDA4NTMzfQ.k7IwXewsyNAtPR4KWYvTvdyL0zfOlPUfxB4GSC-Ppyo
Content-Type: application/json

{
  "vehiculo_id": 1,
  "conductor_id": 1,
  "fecha_salida": "2025-11-12 08:00:00",
  "fecha_llegada": "2025-11-12 12:00:00",
  "origen": "La Rioja",
  "destino": "Córdoba",
  "kilometros": 430,
  "observaciones": "Viaje de prueba"
}
